# Generated by Django 4.1.7 on 2023-03-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='phone_num',
            field=models.CharField(max_length=30, verbose_name='Телефонный номер'),
        ),
    ]
