# Generated by Django 4.1.7 on 2023-04-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_remove_reader_is_admin_reader_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin')], default='owner', max_length=20),
        ),
    ]
