# Generated by Django 4.1.7 on 2023-03-29 17:36

from django.db import migrations, models
import reader.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_alter_reader_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='phone_num',
            field=models.CharField(max_length=30, validators=[reader.validators.validate_phone_num], verbose_name='Телефонный номер'),
        ),
    ]
